USE [medical_db01]
GO

ALTER TABLE [dbo].[APPROVAL] DROP CONSTRAINT [FK_APPROVAL_PATIENT]
GO

ALTER TABLE [dbo].[APPROVAL] DROP CONSTRAINT [FK_APPROVAL_DOCTOR]
GO

/****** Object:  Table [dbo].[APPROVAL]    Script Date: 3/19/2019 2:43:39 PM ******/
DROP TABLE [dbo].[APPROVAL]
GO

/****** Object:  Table [dbo].[APPROVAL]    Script Date: 3/19/2019 2:43:39 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[APPROVAL](
	[App_ID] [varchar](50) NOT NULL CHECK ([App_ID] like '[0-9][0-9][0-9]'),
	[App_Doc_ID] [varchar](50) NOT NULL CHECK ([App_Doc_ID] like '[0-9][0-9][0-9]'),
	[App_Pat_ID] [varchar](50) NOT NULL CHECK ([App_Pat_ID] like '[0-9][0-9][0-9]'),
	[App_Given] [bit] NULL,
 CONSTRAINT [PK_APPROVAL] PRIMARY KEY CLUSTERED 
(
	[App_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[APPROVAL]  WITH CHECK ADD  CONSTRAINT [FK_APPROVAL_DOCTOR] FOREIGN KEY([App_Doc_ID])
REFERENCES [dbo].[DOCTOR] ([Doc_ID])
GO

ALTER TABLE [dbo].[APPROVAL] CHECK CONSTRAINT [FK_APPROVAL_DOCTOR]
GO

ALTER TABLE [dbo].[APPROVAL]  WITH CHECK ADD  CONSTRAINT [FK_APPROVAL_PATIENT] FOREIGN KEY([App_Pat_ID])
REFERENCES [dbo].[PATIENT] ([Pat_ID])
GO

ALTER TABLE [dbo].[APPROVAL] CHECK CONSTRAINT [FK_APPROVAL_PATIENT]
GO


