USE [medical_db01]
GO

ALTER TABLE [dbo].[DIAGNOSIS] DROP CONSTRAINT [FK_DIAGNOSIS_APPOINTMENT]
GO

/****** Object:  Table [dbo].[DIAGNOSIS]    Script Date: 3/19/2019 2:46:16 PM ******/
DROP TABLE [dbo].[DIAGNOSIS]
GO

/****** Object:  Table [dbo].[DIAGNOSIS]    Script Date: 3/19/2019 2:46:16 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[DIAGNOSIS](
	[Diag_ID] [varchar](50) NOT NULL CHECK ([Diag_ID] >=0),
	[Diag_Appt_ID] [varchar](50) NOT NULL CHECK ([Diag_Appt_ID] like '[0-9][0-9][0-9]'),
	[Diag_Desc] [varchar](50) NULL,
 CONSTRAINT [PK_DIAGNOSIS] PRIMARY KEY CLUSTERED 
(
	[Diag_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[DIAGNOSIS]  WITH CHECK ADD  CONSTRAINT [FK_DIAGNOSIS_APPOINTMENT] FOREIGN KEY([Diag_Appt_ID])
REFERENCES [dbo].[APPOINTMENT] ([Appt_ID])
GO

ALTER TABLE [dbo].[DIAGNOSIS] CHECK CONSTRAINT [FK_DIAGNOSIS_APPOINTMENT]
GO


